---
- hosts: all
  roles:
    - role: "common"

    - role: "geerlingguy.docker"
      docker_users:
        - docker

    - role: "geerlingguy.repo-epel"

    - role: "geerlingguy.pip"
      pip_install_packages:
        - name: docker
          state: latest

    - role: "docker_swarm"